### ISSUE TITLE
Error in d01_start_morse.py

### ISSUE THREAD

**Issue by ExperiMentor** [gilesknap/pico-xmas#5]
Code line 4 sets variable 'repeat' to 1000.
But in line 10, repetition is set to a fixed value 1000 rather than using the variable.

Need to change line 10 from:
morse_code(my_morse, 1000)
to:
morse_code(my_morse, repeat)

**Comment by gilesknap** [comment]
Thanks for spotting that. Fixed in 88d2ed1b
